-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.businesses
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    phone_number character varying(30) COLLATE pg_catalog."default",
    plan integer,
    CONSTRAINT businesses_pkey PRIMARY KEY (id),
    CONSTRAINT businesses_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.events
(
    id serial NOT NULL,
    business_id integer,
    fuente character varying(20) COLLATE pg_catalog."default",
    external_id text COLLATE pg_catalog."default",
    title character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    categoria character varying(50) COLLATE pg_catalog."default",
    tipo_plantilla character varying(100) COLLATE pg_catalog."default",
    municipio character varying(100) COLLATE pg_catalog."default",
    territorio character varying(30) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    lat numeric(9, 6),
    lng numeric(9, 6),
    telefono character varying(30) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    website text COLLATE pg_catalog."default",
    es_lluvia boolean DEFAULT false,
    es_carrito boolean DEFAULT false,
    es_cambiador boolean DEFAULT false,
    es_silla_ruedas boolean DEFAULT false,
    es_mascotas boolean DEFAULT false,
    edad_minima numeric,
    multiplicador numeric(3, 2) DEFAULT 1.00,
    fecha_inicio timestamp without time zone NOT NULL,
    fecha_fin timestamp without time zone,
    lugar character varying(255) COLLATE pg_catalog."default",
    price character varying COLLATE pg_catalog."default",
    imagen_url text COLLATE pg_catalog."default",
    tipo_evento character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.families
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    family_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT families_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.family_members
(
    id serial NOT NULL,
    family_id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    age integer NOT NULL,
    CONSTRAINT family_members_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.offers
(
    id serial NOT NULL,
    business_id integer NOT NULL,
    title character varying(150) COLLATE pg_catalog."default" NOT NULL,
    discount character varying(50) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    duration numeric,
    CONSTRAINT offers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.plan_events
(
    plan_id integer NOT NULL,
    event_id integer NOT NULL,
    event_order integer NOT NULL,
    CONSTRAINT plan_events_pkey PRIMARY KEY (plan_id, event_id)
);

CREATE TABLE IF NOT EXISTS public.plans
(
    id serial NOT NULL,
    creator_id integer,
    title character varying(150) COLLATE pg_catalog."default" NOT NULL,
    is_recommendation boolean DEFAULT false,
    rating integer,
    CONSTRAINT plans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_favorite_events
(
    user_id integer NOT NULL,
    event_id integer NOT NULL,
    saved_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_favorite_events_pkey PRIMARY KEY (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS public.user_favorite_plans
(
    user_id integer NOT NULL,
    plan_id integer NOT NULL,
    saved_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_favorite_plans_pkey PRIMARY KEY (user_id, plan_id)
);

CREATE TABLE IF NOT EXISTS public.user_selected_recommendations
(
    user_id integer NOT NULL,
    event_id integer NOT NULL,
    selected_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_selected_recommendations_pkey PRIMARY KEY (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.businesses
    ADD CONSTRAINT businesses_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS businesses_user_id_key
    ON public.businesses(user_id);


ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_business_id_fkey FOREIGN KEY (business_id)
    REFERENCES public.businesses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.families
    ADD CONSTRAINT families_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.family_members
    ADD CONSTRAINT family_members_family_id_fkey FOREIGN KEY (family_id)
    REFERENCES public.families (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.offers
    ADD CONSTRAINT offers_business_id_fkey FOREIGN KEY (business_id)
    REFERENCES public.businesses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.plan_events
    ADD CONSTRAINT plan_events_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.plan_events
    ADD CONSTRAINT plan_events_plan_id_fkey FOREIGN KEY (plan_id)
    REFERENCES public.plans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.plans
    ADD CONSTRAINT plans_creator_id_fkey FOREIGN KEY (creator_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_favorite_events
    ADD CONSTRAINT user_favorite_events_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_favorite_events
    ADD CONSTRAINT user_favorite_events_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_favorite_plans
    ADD CONSTRAINT user_favorite_plans_plan_id_fkey FOREIGN KEY (plan_id)
    REFERENCES public.plans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_favorite_plans
    ADD CONSTRAINT user_favorite_plans_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_selected_recommendations
    ADD CONSTRAINT usr_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_selected_recommendations
    ADD CONSTRAINT usr_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;
