/**
 * Modelo mock de eventos.
 * Estructura compatible con la tabla `events` de init.sql.
 * Este archivo es la fuente de datos en memoria para desarrollo local sin PostgreSQL.
 *
 * Una vez que PostgreSQL esté levantado, los repositories cambiarán de este mock a Prisma.
 */

export const mockEvents = [
  {
    id: 1,
    business_id: null,
    fuente: 'mock',
    external_id: null,
    title: 'Guggenheim Txiki',
    description: 'Museo Guggenheim con talleres para familias',
    categoria: 'Museos',
    tipo_plantilla: null,
    municipio: 'Bilbao',
    territorio: 'Bizkaia',
    address: 'Avenida de Abandoibarra, 2, 48009 Bilbao',
    lat: 43.218521,
    lng: -2.967119,
    telefono: '944359000',
    email: 'visitas@guggenheim.es',
    website: 'https://www.guggenheim-bilbao.es',
    es_interior: true,
    es_carrito: true,
    es_cambiador: true,
    es_silla_ruedas: true,
    es_mascotas: false,
    edad_minima: 4,
    multiplicador: 1.0,
    fecha_inicio: new Date('2026-06-05T09:00:00Z'),
    fecha_fin: new Date('2026-12-31T18:00:00Z'),
    lugar: 'Bilbao, Centro',
    price: 'Desde 12€',
    imagen_url: 'https://images.unsplash.com/photo-1543325164-9ed3ebc18221?q=80&w=600&auto=format&fit=crop',
    tipo_evento: 'Museo',
  },
  {
    id: 2,
    business_id: null,
    fuente: 'mock',
    external_id: null,
    title: 'Parque de Doña Casilda',
    description: 'Pulmón verde del centro de Bilbao con zonas de juegos',
    categoria: 'Parques',
    tipo_plantilla: null,
    municipio: 'Bilbao',
    territorio: 'Bizkaia',
    address: 'Parque de Doña Casilda, Bilbao',
    lat: 43.263055,
    lng: -2.945556,
    telefono: null,
    email: null,
    website: null,
    es_interior: false,
    es_carrito: true,
    es_cambiador: false,
    es_silla_ruedas: true,
    es_mascotas: true,
    edad_minima: 0,
    multiplicador: 1.0,
    fecha_inicio: new Date('2026-01-01T08:00:00Z'),
    fecha_fin: null,
    lugar: 'Bilbao, Indautxu',
    price: 'Gratis',
    imagen_url: 'https://images.unsplash.com/photo-1601000678887-b935cd4d7d0a?q=80&w=600&auto=format&fit=crop',
    tipo_evento: 'Parque',
  },
  {
    id: 3,
    business_id: null,
    fuente: 'mock',
    external_id: null,
    title: 'Taller de Cerámica Familiar',
    description: 'Taller interactivo de 2 horas para toda la familia',
    categoria: 'Talleres',
    tipo_plantilla: null,
    municipio: 'Bilbao',
    territorio: 'Bizkaia',
    address: 'Casco Viejo, Bilbao',
    lat: 43.25516,
    lng: -2.927481,
    telefono: '944160156',
    email: 'info@tallerceramica.es',
    website: null,
    es_interior: true,
    es_carrito: false,
    es_cambiador: true,
    es_silla_ruedas: false,
    es_mascotas: false,
    edad_minima: 5,
    multiplicador: 1.2,
    fecha_inicio: new Date('2026-06-10T16:00:00Z'),
    fecha_fin: new Date('2026-12-20T18:00:00Z'),
    lugar: 'Bilbao, Casco Viejo',
    price: '25€/familia',
    imagen_url: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?q=80&w=600&auto=format&fit=crop',
    tipo_evento: 'Taller',
  },
  {
    id: 4,
    business_id: null,
    fuente: 'mock',
    external_id: null,
    title: 'Ruta Bosque de Oma',
    description: 'Excursión por el bosque pintado, obra de arte al aire libre',
    categoria: 'Naturaleza',
    tipo_plantilla: null,
    municipio: 'Kortezubi',
    territorio: 'Bizkaia',
    address: 'Urdaibai, Kortezubi',
    lat: 43.363,
    lng: -2.665,
    telefono: '944650795',
    email: null,
    website: null,
    es_interior: false,
    es_carrito: false,
    es_cambiador: false,
    es_silla_ruedas: false,
    es_mascotas: true,
    edad_minima: 3,
    multiplicador: 1.0,
    fecha_inicio: new Date('2026-06-01T09:00:00Z'),
    fecha_fin: null,
    lugar: 'Kortezubi, Urdaibai',
    price: 'Gratis',
    imagen_url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=600&auto=format&fit=crop',
    tipo_evento: 'Senderismo',
  },
  {
    id: 5,
    business_id: null,
    fuente: 'mock',
    external_id: null,
    title: 'Restaurante TxokoKids',
    description: 'Restaurante con txikipark vigilado para niños',
    categoria: 'Restaurantes',
    tipo_plantilla: null,
    municipio: 'Getxo',
    territorio: 'Bizkaia',
    address: 'Getxo, Vizcaya',
    lat: 43.2959,
    lng: -3.0287,
    telefono: '944308812',
    email: 'info@txokokids.es',
    website: 'https://txokokids.es',
    es_interior: true,
    es_carrito: true,
    es_cambiador: true,
    es_silla_ruedas: true,
    es_mascotas: false,
    edad_minima: 0,
    multiplicador: 1.0,
    fecha_inicio: new Date('2026-01-01T12:00:00Z'),
    fecha_fin: null,
    lugar: 'Getxo',
    price: '15-25€/persona',
    imagen_url: 'https://images.unsplash.com/photo-1519340241574-2cefa556ec4b?q=80&w=600&auto=format&fit=crop',
    tipo_evento: 'Restaurante',
  },
  {
    id: 6,
    business_id: null,
    fuente: 'mock',
    external_id: null,
    title: 'Acuario de Getxo',
    description: 'Acuario interactivo con especies marinas del Cantábrico',
    categoria: 'Museos',
    tipo_plantilla: null,
    municipio: 'Getxo',
    territorio: 'Bizkaia',
    address: 'Muelle de las Arenas, Getxo',
    lat: 43.2987,
    lng: -3.0298,
    telefono: '944914234',
    email: 'info@acuariogetxo.es',
    website: null,
    es_interior: true,
    es_carrito: true,
    es_cambiador: true,
    es_silla_ruedas: true,
    es_mascotas: false,
    edad_minima: 2,
    multiplicador: 1.0,
    fecha_inicio: new Date('2026-01-01T10:00:00Z'),
    fecha_fin: null,
    lugar: 'Getxo',
    price: '8€/persona',
    imagen_url: 'https://images.unsplash.com/photo-1550335685-72658b621201?q=80&w=600&auto=format&fit=crop',
    tipo_evento: 'Acuario',
  },
  {
    id: 7,
    business_id: null,
    fuente: 'mock',
    external_id: null,
    title: 'Pintxos en la Ribera',
    description: 'Ruta de pintxos tradicional vascos en el casco viejo',
    categoria: 'Gastronomía',
    tipo_plantilla: null,
    municipio: 'Bilbao',
    territorio: 'Bizkaia',
    address: 'Casco Viejo, Bilbao',
    lat: 43.2551,
    lng: -2.9274,
    telefono: null,
    email: null,
    website: null,
    es_interior: false,
    es_carrito: true,
    es_cambiador: false,
    es_silla_ruedas: true,
    es_mascotas: false,
    edad_minima: 5,
    multiplicador: 1.0,
    fecha_inicio: new Date('2026-01-01T11:00:00Z'),
    fecha_fin: null,
    lugar: 'Bilbao, Casco Viejo',
    price: '20-30€/adulto',
    imagen_url: 'https://images.unsplash.com/photo-1597318185211-c1edd7235f1b?q=80&w=600&auto=format&fit=crop',
    tipo_evento: 'Ruta gastronómica',
  },
];

export default mockEvents;
