/**
 * Datos mock de actividades (MVP, en memoria).
 *
 * Alineados con el shape documentado en docs/api.md. Incluye actividades
 * `approved` y al menos una `pending` (no debe aparecer en los listados públicos).
 * Reemplazará a PostgreSQL/Prisma en una rama posterior (ver docs/database.md).
 */
export const mockActivities = [
  {
    id: 'act-001',
    title: 'Aquarium de Donostia',
    category: 'museo',
    province: 'Gipuzkoa',
    municipality: 'Donostia-San Sebastián',
    recommendedAgeMin: 0,
    recommendedAgeMax: 12,
    priceType: 'medium',
    estimatedFamilyCost: 38,
    isIndoor: true,
    rainSuitable: true,
    strollerFriendly: true,
    hasToilet: true,
    hasChangingTable: true,
    averageRating: 4.6,
    status: 'approved',
  },
  {
    id: 'act-002',
    title: 'Monte Igueldo',
    category: 'aire-libre',
    province: 'Gipuzkoa',
    municipality: 'Donostia-San Sebastián',
    recommendedAgeMin: 3,
    recommendedAgeMax: 12,
    priceType: 'medium',
    estimatedFamilyCost: 30,
    isIndoor: false,
    rainSuitable: false,
    strollerFriendly: false,
    hasToilet: true,
    hasChangingTable: false,
    averageRating: 4.3,
    status: 'approved',
  },
  {
    id: 'act-003',
    title: 'Parque de Doña Casilda',
    category: 'parque',
    province: 'Bizkaia',
    municipality: 'Bilbao',
    recommendedAgeMin: 0,
    recommendedAgeMax: 10,
    priceType: 'free',
    estimatedFamilyCost: 0,
    isIndoor: false,
    rainSuitable: false,
    strollerFriendly: true,
    hasToilet: true,
    hasChangingTable: true,
    averageRating: 4.7,
    status: 'approved',
  },
  {
    id: 'act-004',
    title: 'Museo Guggenheim (taller familiar)',
    category: 'museo',
    province: 'Bizkaia',
    municipality: 'Bilbao',
    recommendedAgeMin: 4,
    recommendedAgeMax: 12,
    priceType: 'high',
    estimatedFamilyCost: 50,
    isIndoor: true,
    rainSuitable: true,
    strollerFriendly: true,
    hasToilet: true,
    hasChangingTable: true,
    averageRating: 4.5,
    status: 'approved',
  },
  {
    id: 'act-005',
    title: 'Playa de la Concha',
    category: 'playa',
    province: 'Gipuzkoa',
    municipality: 'Donostia-San Sebastián',
    recommendedAgeMin: 0,
    recommendedAgeMax: 12,
    priceType: 'free',
    estimatedFamilyCost: 0,
    isIndoor: false,
    rainSuitable: false,
    strollerFriendly: true,
    hasToilet: true,
    hasChangingTable: false,
    averageRating: 4.8,
    status: 'approved',
  },
  {
    // Pendiente de moderación: NO debe aparecer en /api/activities ni en recomendaciones.
    id: 'act-006',
    title: 'Parque indoor (pendiente de validación)',
    category: 'ocio-indoor',
    province: 'Araba',
    municipality: 'Vitoria-Gasteiz',
    recommendedAgeMin: 1,
    recommendedAgeMax: 8,
    priceType: 'low',
    estimatedFamilyCost: 12,
    isIndoor: true,
    rainSuitable: true,
    strollerFriendly: true,
    hasToilet: true,
    hasChangingTable: true,
    averageRating: 0,
    status: 'pending',
  },
];

export default mockActivities;
