/**
 * Datos mock de eventos familiares en Euskadi.
 *
 * MVP / PRIMERA INTEGRACIÓN: shape EXACTO de la tabla `events` de
 * backend/src/models/init.sql (snake_case). Datos ficticios para desarrollo de la API
 * sin depender todavía de PostgreSQL real (runtime mock, ADR-0001).
 *
 * `fecha_inicio` / `fecha_fin` en ISO 8601 para que Prisma (futuro) los acepte tal cual.
 */
export const mockEvents = [
  {
    id: 1,
    business_id: 1,
    fuente: 'manual',
    external_id: null,
    title: 'Exposición interactiva en el museo',
    description: 'Sala sensorial para peques con zona de juego y cuentacuentos.',
    categoria: 'museo',
    tipo_plantilla: null,
    municipio: 'Bilbao',
    territorio: 'Bizkaia',
    address: 'Plaza del Museo, 2',
    lat: 43.2645,
    lng: -2.9342,
    telefono: '944000001',
    email: null,
    website: null,
    es_lluvia: true,
    es_carrito: true,
    es_cambiador: true,
    es_silla_ruedas: true,
    es_mascotas: false,
    edad_minima: 0,
    multiplicador: 1.0,
    fecha_inicio: '2026-06-10T10:00:00',
    fecha_fin: '2026-06-10T13:00:00',
    lugar: 'Museo de Bellas Artes',
    price: 'Gratis',
    imagen_url: null,
    tipo_evento: 'exposicion',
  },
  {
    id: 2,
    business_id: null,
    fuente: 'scraper',
    external_id: 'ext-getxo-02',
    title: 'Juegos en la playa de Ereaga',
    description: 'Actividad al aire libre con monitores en la arena.',
    categoria: 'playa',
    tipo_plantilla: null,
    municipio: 'Getxo',
    territorio: 'Bizkaia',
    address: 'Playa de Ereaga',
    lat: 43.3389,
    lng: -3.0167,
    telefono: null,
    email: null,
    website: null,
    es_lluvia: false,
    es_carrito: true,
    es_cambiador: false,
    es_silla_ruedas: false,
    es_mascotas: true,
    edad_minima: 3,
    multiplicador: 1.0,
    fecha_inicio: '2026-06-15T11:00:00',
    fecha_fin: null,
    lugar: 'Playa de Ereaga',
    price: 'Gratis',
    imagen_url: null,
    tipo_evento: 'actividad',
  },
  {
    id: 3,
    business_id: 2,
    fuente: 'manual',
    external_id: null,
    title: 'Taller de cocina para familias',
    description: 'Taller a cubierto donde peques y mayores cocinan juntos.',
    categoria: 'taller',
    tipo_plantilla: 'taller-cocina',
    municipio: 'Bilbao',
    territorio: 'Bizkaia',
    address: 'Calle Somera, 10',
    lat: 43.2587,
    lng: -2.9237,
    telefono: '944000003',
    email: 'info@tallerbilbao.eus',
    website: 'https://example.eus',
    es_lluvia: true,
    es_carrito: true,
    es_cambiador: true,
    es_silla_ruedas: true,
    es_mascotas: false,
    edad_minima: 4,
    multiplicador: 1.0,
    fecha_inicio: '2026-07-05T17:00:00',
    fecha_fin: '2026-07-05T19:00:00',
    lugar: 'Aula gastronómica',
    price: '8 €',
    imagen_url: null,
    tipo_evento: 'taller',
  },
  {
    id: 4,
    business_id: 3,
    fuente: 'manual',
    external_id: null,
    title: 'Visita al acuario',
    description: 'Recorrido por el acuario con túnel de tiburones.',
    categoria: 'museo',
    tipo_plantilla: null,
    municipio: 'Donostia-San Sebastián',
    territorio: 'Gipuzkoa',
    address: 'Plaza Carlos Blasco de Imaz, 1',
    lat: 43.3231,
    lng: -1.9912,
    telefono: '943000004',
    email: null,
    website: null,
    es_lluvia: true,
    es_carrito: true,
    es_cambiador: true,
    es_silla_ruedas: true,
    es_mascotas: false,
    edad_minima: 0,
    multiplicador: 1.0,
    fecha_inicio: '2026-06-20T10:30:00',
    fecha_fin: '2026-06-20T12:30:00',
    lugar: 'Aquarium',
    price: '12 €',
    imagen_url: null,
    tipo_evento: 'exposicion',
  },
  {
    id: 5,
    business_id: null,
    fuente: 'scraper',
    external_id: 'ext-donosti-05',
    title: 'Ruta de naturaleza en Ulia',
    description: 'Sendero familiar con vistas al mar (no apto para carrito).',
    categoria: 'naturaleza',
    tipo_plantilla: null,
    municipio: 'Donostia-San Sebastián',
    territorio: 'Gipuzkoa',
    address: 'Monte Ulia',
    lat: 43.3289,
    lng: -1.9512,
    telefono: null,
    email: null,
    website: null,
    es_lluvia: false,
    es_carrito: false,
    es_cambiador: false,
    es_silla_ruedas: false,
    es_mascotas: true,
    edad_minima: 6,
    multiplicador: 1.0,
    fecha_inicio: '2026-07-12T09:30:00',
    fecha_fin: null,
    lugar: 'Monte Ulia',
    price: '5 €',
    imagen_url: null,
    tipo_evento: 'actividad',
  },
  {
    id: 6,
    business_id: 4,
    fuente: 'manual',
    external_id: null,
    title: 'Espectáculo de marionetas',
    description: 'Función de teatro de marionetas en sala cubierta.',
    categoria: 'teatro',
    tipo_plantilla: null,
    municipio: 'Vitoria-Gasteiz',
    territorio: 'Araba',
    address: 'Calle Francia, 24',
    lat: 42.8467,
    lng: -2.6716,
    telefono: '945000006',
    email: null,
    website: null,
    es_lluvia: true,
    es_carrito: true,
    es_cambiador: true,
    es_silla_ruedas: true,
    es_mascotas: false,
    edad_minima: 2,
    multiplicador: 1.0,
    fecha_inicio: '2026-07-18T18:00:00',
    fecha_fin: '2026-07-18T19:00:00',
    lugar: 'Teatro Principal',
    price: '10 €',
    imagen_url: null,
    tipo_evento: 'espectaculo',
  },
  {
    id: 7,
    business_id: null,
    fuente: 'scraper',
    external_id: 'ext-vitoria-07',
    title: 'Juegos en el parque de Olárizu',
    description: 'Gran zona verde con praderas y rutas accesibles con carrito.',
    categoria: 'parque',
    tipo_plantilla: null,
    municipio: 'Vitoria-Gasteiz',
    territorio: 'Araba',
    address: 'Olárizu',
    lat: 42.8331,
    lng: -2.6589,
    telefono: null,
    email: null,
    website: null,
    es_lluvia: false,
    es_carrito: true,
    es_cambiador: false,
    es_silla_ruedas: true,
    es_mascotas: true,
    edad_minima: 0,
    multiplicador: 1.0,
    fecha_inicio: '2026-06-08T10:00:00',
    fecha_fin: null,
    lugar: 'Parque de Olárizu',
    price: 'Gratis',
    imagen_url: null,
    tipo_evento: 'actividad',
  },
  {
    id: 8,
    business_id: 5,
    fuente: 'manual',
    external_id: null,
    title: 'Granja-escuela en Karrantza',
    description: 'Visita a la granja con animales y huerto.',
    categoria: 'naturaleza',
    tipo_plantilla: null,
    municipio: 'Karrantza',
    territorio: 'Bizkaia',
    address: 'Barrio Biáñez, 23',
    lat: 43.2058,
    lng: -3.3686,
    telefono: '946000008',
    email: null,
    website: null,
    es_lluvia: false,
    es_carrito: false,
    es_cambiador: true,
    es_silla_ruedas: false,
    es_mascotas: true,
    edad_minima: 2,
    multiplicador: 1.0,
    fecha_inicio: '2026-06-28T11:00:00',
    fecha_fin: '2026-06-28T14:00:00',
    lugar: 'Karpin',
    price: '9 €',
    imagen_url: null,
    tipo_evento: 'actividad',
  },
  {
    id: 9,
    business_id: null,
    fuente: 'scraper',
    external_id: 'ext-tolosa-09',
    title: 'Feria familiar de Tolosa',
    description: 'Feria al aire libre con puestos y actividades infantiles.',
    categoria: 'feria',
    tipo_plantilla: null,
    municipio: 'Tolosa',
    territorio: 'Gipuzkoa',
    address: 'Plaza Euskal Herria',
    lat: 43.1339,
    lng: -2.0786,
    telefono: null,
    email: null,
    website: null,
    es_lluvia: false,
    es_carrito: true,
    es_cambiador: true,
    es_silla_ruedas: true,
    es_mascotas: false,
    edad_minima: 0,
    multiplicador: 1.0,
    fecha_inicio: '2026-07-22T17:00:00',
    fecha_fin: '2026-07-22T21:00:00',
    lugar: 'Plaza Euskal Herria',
    price: 'Gratis',
    imagen_url: null,
    tipo_evento: 'feria',
  },
  {
    id: 10,
    business_id: 1,
    fuente: 'manual',
    external_id: null,
    title: 'Iniciación al baloncesto',
    description: 'Taller deportivo en pabellón cubierto para mayores de 6 años.',
    categoria: 'deporte',
    tipo_plantilla: 'taller-deporte',
    municipio: 'Bilbao',
    territorio: 'Bizkaia',
    address: 'Polideportivo Miribilla',
    lat: 43.2497,
    lng: -2.9275,
    telefono: '944000010',
    email: null,
    website: null,
    es_lluvia: true,
    es_carrito: false,
    es_cambiador: false,
    es_silla_ruedas: false,
    es_mascotas: false,
    edad_minima: 6,
    multiplicador: 1.0,
    fecha_inicio: '2026-06-25T16:00:00',
    fecha_fin: '2026-06-25T17:30:00',
    lugar: 'Polideportivo Miribilla',
    price: '6 €',
    imagen_url: null,
    tipo_evento: 'taller',
  },
];

export default mockEvents;
