-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.businesses
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    phone_number character varying(30) COLLATE pg_catalog."default",
    plan integer,
    nif character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT businesses_pkey PRIMARY KEY (id),
    CONSTRAINT businesses_user_id_key UNIQUE (user_id),
    CONSTRAINT businesses_nif_key UNIQUE (nif)
);

CREATE TABLE IF NOT EXISTS public.events
(
    id serial NOT NULL,
    business_id integer,
    fuente character varying(255) COLLATE pg_catalog."default", -- CAMBIO FULL STACK: Ampliado de 20 a 255 para soportar URLs del CSV
    external_id text COLLATE pg_catalog."default",
    title character varying(150) COLLATE pg_catalog.\"default\" NOT NULL,
    description text COLLATE pg_catalog."default",
    categoria character varying(50) COLLATE pg_catalog."default",
    tipo_plantilla character varying(100) COLLATE pg_catalog."default",
    municipio character varying(100) COLLATE pg_catalog."default",
    territorio character varying(30) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    lat numeric(9, 6),
    lng numeric(9, 6),
    telefono character varying(30) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    website text COLLATE pg_catalog."default",
    es_interior boolean DEFAULT false,
    es_carrito boolean DEFAULT false,
    es_cambiador boolean DEFAULT false,
    es_silla_ruedas boolean DEFAULT false,
    es_mascotas boolean DEFAULT false,
    edad_minima integer DEFAULT 0,
    multiplicador numeric(3, 2) DEFAULT 1.00,
    fecha_inicio date NOT NULL,
    fecha_fin date,
    lugar character varying(150) COLLATE pg_catalog."default",
    price character varying(100) COLLATE pg_catalog."default",
    imagen_url text COLLATE pg_catalog."default",
    tipo_evento character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.families
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    alias character varying(50) COLLATE pg_catalog."default" NOT NULL,
    municipio character varying(100) COLLATE pg_catalog."default",
    territorio character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT families_pkey PRIMARY KEY (id),
    CONSTRAINT families_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.family_children
(
    id serial NOT NULL,
    family_id integer NOT NULL,
    birth_date date NOT NULL,
    CONSTRAINT family_children_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.plans
(
    id serial NOT NULL,
    creator_id integer,
    title character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    is_public boolean DEFAULT false,
    CONSTRAINT plans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    event_id integer NOT NULL,
    rating integer NOT NULL,
    comment text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_pkey PRIMARY KEY (id),
    CONSTRAINT reviews_rating_check CHECK (rating >= 1 AND rating <= 5)
);

CREATE TABLE IF NOT EXISTS public.user_favorite_events
(
    user_id integer NOT NULL,
    event_id integer NOT NULL,
    CONSTRAINT user_favorite_events_pkey PRIMARY KEY (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS public.user_favorite_plans
(
    user_id integer NOT NULL,
    plan_id integer NOT NULL,
    CONSTRAINT user_favorite_plans_pkey PRIMARY KEY (user_id, plan_id)
);

CREATE TABLE IF NOT EXISTS public.user_selected_recommendations
(
    user_id integer NOT NULL,
    event_id integer NOT NULL,
    CONSTRAINT user_selected_recommendations_pkey PRIMARY KEY (user_id, event_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" DEFAULT 'family'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.businesses
    ADD CONSTRAINT businesses_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.events
    ADD CONSTRAINT events_business_id_fkey FOREIGN KEY (business_id)
    REFERENCES public.businesses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.families
    ADD CONSTRAINT families_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.family_children
    ADD CONSTRAINT family_children_family_id_fkey FOREIGN KEY (family_id)
    REFERENCES public.families (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.plans
    ADD CONSTRAINT plans_creator_id_fkey FOREIGN KEY (creator_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_favorite_events
    ADD CONSTRAINT user_favorite_events_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_favorite_events
    ADD CONSTRAINT user_favorite_events_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_favorite_plans
    ADD CONSTRAINT user_favorite_plans_plan_id_fkey FOREIGN KEY (plan_id)
    REFERENCES public.plans (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_favorite_plans
    ADD CONSTRAINT user_favorite_plans_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_selected_recommendations
    ADD CONSTRAINT usr_event_id_fkey FOREIGN KEY (event_id)
    REFERENCES public.events (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_selected_recommendations
    ADD CONSTRAINT usr_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;